#!/bin/bash

# Get the directory where the script is located
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Find all .go files in the script's directory, excluding *_test.go files
go_files=$(find "$script_dir" -maxdepth 1 -name "*.go" ! -name "*_test.go")

# Run all .go files with any provided arguments
echo "-------------------------- "
echo "|--  Testing SiteStat  --| "
echo "-------------------------- "
go run $go_files $@ 